2021-09-09 16:09:52,640 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:55]
2021-09-09 16:10:52,315 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:55]
2021-09-09 16:11:08,322 ERROR: Exception on /favicon.ico [GET] [in c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1489, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1471, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\ctx.py", line 367, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\werkzeug\routing.py", line 2032, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1383, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\app.py", line 1323, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\rlgava\documents\mestrado\python\hachi_project\flask_tutorial\tutorial\hachi_amb\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
2021-09-09 16:31:24,310 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 16:34:04,154 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 16:39:32,294 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 16:45:58,672 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 16:48:24,313 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 16:52:23,280 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:57]
2021-09-09 18:12:11,075 INFO: Microblog startup [in C:\Users\rlgava\Documents\Mestrado\Python\Hachi_Project\flask_tutorial\tutorial\app\__init__.py:59]
